const schemes = {
  "expertOpinion": {
    "label": "Expert Opinion",
    "variables": [
      {
        "key": "E"
      },
      {
        "key": "S"
      },
      {
        "key": "A"
      }
    ],
    "data": "Source E is an expert in subject domain S containing proposition A"
  }
}


// eventually, these factory functions should be autogenerated from the data in the object above
const createExpertOpinionSchema = ({ variables }) => ({
  variables,
  display() {
    return `Source ${this.variables['E']} is an expert in subject domain ${this.variables['S']} containing proposition ${this.variables['A']}.`
  }
})

const anExpertOpinion = createExpertOpinionSchema({
  variables: {
    'E': 'Doug',
    'S': 'pool',
    'A': 'pool is the best sport'
  }
})

console.log(anExpertOpinion.display())