export const encodings = [
"i'm",
"i'm going",
"i'm going to",
"i'm going to give",
"i'm going to give it",
"i'm going to give it a",
"i'm going to give it a marginal",
"i'm going to give it a marginal thumbs",
"i'm going to give it a marginal thumbs up",
"i'm going to give it a marginal thumbs up .",
"i'm going to give it a marginal thumbs up . i",
"i'm going to give it a marginal thumbs up . i liked",
"i'm going to give it a marginal thumbs up . i liked it",
"i'm going to give it a marginal thumbs up . i liked it just",
"i'm going to give it a marginal thumbs up . i liked it just enough",
"i'm going to give it a marginal thumbs up . i liked it just enough .",
"enough .",
"just enough .",
"it just enough .",
"liked it just enough .",
"i liked it just enough .",
". i liked it just enough .",
"up . i liked it just enough .",
"thumbs up . i liked it just enough .",
"marginal thumbs up . i liked it just enough .",
"a marginal thumbs up . i liked it just enough .",
"it a marginal thumbs up . i liked it just enough .",
"give it a marginal thumbs up . i liked it just enough .",
"to give it a marginal thumbs up . i liked it just enough .",
"going to give it a marginal thumbs up . i liked it just enough .",
"i'm going to give it a marginal thumbs up . i liked it just enough .",
"i'm give a going to it thumbs . up marginal i just it liked enough .",
"i'm give a going to it thumbs . up marginal i it just liked enough .",
"i'm give a going to it thumbs . marginal up i it just liked enough .",
"i'm give going a to it thumbs . marginal up i it just liked enough .",
"i'm give going a to it thumbs marginal . up i it just liked enough .",
"i'm give going a to it thumbs marginal . up i it liked just enough .",
"i'm going give a to it thumbs marginal . up i it liked just enough .",
"i'm going give a to it marginal thumbs . up i it liked just enough .",
"going i'm give a to it marginal thumbs . up i it liked just enough .",
"going i'm give to a it marginal thumbs . up i it liked just enough .",
"going i'm give to a it marginal thumbs . up i it liked just . enough",
"going i'm give to it a marginal thumbs . up i it liked just . enough",
"i'm going give to it a marginal thumbs . up i it liked just . enough",
"i'm going give to it a marginal thumbs . up i liked it just . enough",
"i'm going give to it a marginal thumbs up . i liked it just . enough",
"i'm going give to it a marginal thumbs up . i liked it just enough .",
"i'm going to give it a marginal thumbs up . i liked it just enough .",
"a",
"a deliciously",
"a deliciously nonsensical",
"a deliciously nonsensical comedy",
"a deliciously nonsensical comedy about",
"a deliciously nonsensical comedy about a",
"a deliciously nonsensical comedy about a city",
"a deliciously nonsensical comedy about a city coming",
"a deliciously nonsensical comedy about a city coming apart",
"a deliciously nonsensical comedy about a city coming apart at",
"a deliciously nonsensical comedy about a city coming apart at its",
"a deliciously nonsensical comedy about a city coming apart at its seams",
"a deliciously nonsensical comedy about a city coming apart at its seams .",
"seams .",
"its seams .",
"at its seams .",
"apart at its seams .",
"coming apart at its seams .",
"city coming apart at its seams .",
"a city coming apart at its seams .",
"about a city coming apart at its seams .",
"comedy about a city coming apart at its seams .",
"nonsensical comedy about a city coming apart at its seams .",
"deliciously nonsensical comedy about a city coming apart at its seams .",
"a deliciously nonsensical comedy about a city coming apart at its seams .",
"deliciously a nonsensical comedy a about city coming at apart its .",
"deliciously a nonsensical comedy a about city coming at apart its . seams",
"a deliciously nonsensical comedy a about city coming at apart its . seams",
"a deliciously nonsensical comedy a about coming city at apart its . seams",
"a deliciously nonsensical comedy a about city coming at apart its . seams",
"a deliciously nonsensical comedy a about city coming at apart its seams .",
"a deliciously nonsensical comedy a about city coming apart at its seams .",
"a deliciously nonsensical comedy a about coming city apart at its seams .",
"a deliciously comedy nonsensical a about coming city apart at its seams .",
"a deliciously comedy nonsensical about a coming city apart at its seams .",
"a deliciously nonsensical comedy about a coming city apart at its seams .",
"a deliciously nonsensical comedy about a city coming apart at its seams .",
"a deliciously nonsensical comedy about a coming city apart at its seams .",
"a deliciously nonsensical comedy about a city coming apart at its seams ."
]